spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
  jpa:
    show-sql: true
