GET http://localhost:8081/users

###
GET http://localhost:8081/users/petrov

###
POST http://localhost:8081/users
Content-Type: application/json

{
  "account": "agafonov",
  "name": "Олег",
  "lastname": "Агафонов"
}

###
PUT http://localhost:8081/users/petrov
Content-Type: application/json

{
  "account": "petrov",
  "name": "Андрей",
  "lastname": "Агафонов"
}

###
DELETE http://localhost:8081/users/petrov